name: Filter Suspicious Configurations (پالایش کانفیگ‌های مشکوک و کامیت گزارش)

on:
  workflow_dispatch: # اجازه اجرای دستی از تب Actions
    inputs:
      links_file_path:
        description: 'مسیر فایل حاوی لیست URLها (نسبت به ریشه مخزن)'
        required: true
        default: 'links.txt'
      report_output_name:
        description: 'نام فایل گزارش خروجی در ریشه مخزن'
        required: true
        default: 'suspicious_configs_report.txt'
  schedule:
    - cron: '0 3 * * *' # مثال: هر روز ساعت ۳:۰۰ بامداد به وقت UTC اجرا می‌شود

env:
  # این ثابت‌ها به اسکریپت پایتون پاس داده می‌شوند
  MIN_PERCENT25_COUNT: 15
  MAX_CONFIG_LENGTH: 1500
  PYTHON_SCRIPT_NAME: 'filter_configs.py' # نام اسکریپت پایتون شما

jobs:
  filter_and_report:
    name: Filter and Commit Report (فیلتر و کامیت گزارش)
    runs-on: ubuntu-latest
    # دسترسی لازم برای نوشتن در مخزن (کامیت کردن فایل)
    permissions:
      contents: write

    steps:
      - name: Harden Runner (ایمن‌سازی اجراکننده)
        uses: step-security/harden-runner@v2.9.0
        with:
          egress-policy: audit

      - name: Checkout repository (دریافت کد مخزن)
        # اصلاح شده: استفاده از تگ نسخه به جای SHA کامل
        uses: actions/checkout@v4.1.6

      - name: Set up Python (راه‌اندازی پایتون)
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies (نصب وابستگی‌های پایتون)
        run: pip install requests

      - name: Determine file paths (تعیین مسیرهای فایل)
        id: set_paths
        run: |
          LINKS_FILE="${{ github.event.inputs.links_file_path || 'links.txt' }}"
          REPORT_FILE="${{ github.event.inputs.report_output_name || 'suspicious_configs_report.txt' }}"
          echo "LINKS_FILE_TO_USE=$LINKS_FILE" >> $GITHUB_ENV
          echo "REPORT_FILE_TO_USE=$REPORT_FILE" >> $GITHUB_ENV
          echo "استفاده از فایل لینک‌ها: $LINKS_FILE"
          echo "گزارش در این فایل در ریشه مخزن ایجاد خواهد شد: $REPORT_FILE"

      - name: Check if links file exists (بررسی وجود فایل لینک‌ها)
        run: |
          if [ ! -f "${{ env.LINKS_FILE_TO_USE }}" ]; then
            echo "::error file=${{ env.LINKS_FILE_TO_USE }}::فایل لینک‌ها یافت نشد. لطفاً آن را ایجاد کنید یا مسیر را بررسی نمایید."
            exit 1
          fi

      - name: Run configuration filter script (اجرای اسکریپت فیلتر کانفیگ)
        run: |
          python ${{ env.PYTHON_SCRIPT_NAME }} "${{ env.LINKS_FILE_TO_USE }}" "${{ env.REPORT_FILE_TO_USE }}"
          echo "فایل گزارش تولید شد در مسیر: ${{ env.REPORT_FILE_TO_USE }}"
        env:
          MIN_PERCENT25_COUNT: ${{ env.MIN_PERCENT25_COUNT }}
          MAX_CONFIG_LENGTH: ${{ env.MAX_CONFIG_LENGTH }}

      - name: Commit and push report (کامیت و پوش کردن گزارش)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id}}+${{ github.actor }}@users.noreply.github.com"

          if [ ! -f "${{ env.REPORT_FILE_TO_USE }}" ]; then
            echo "فایل گزارش ${{ env.REPORT_FILE_TO_USE }} یافت نشد. از کامیت کردن صرف نظر می‌شود."
            exit 0
          fi
          
          git add "${{ env.REPORT_FILE_TO_USE }}"
          
          if git diff --staged --quiet; then
            echo "هیچ تغییری در فایل ${{ env.REPORT_FILE_TO_USE }} برای کامیت کردن وجود ندارد."
            exit 0
          fi
          
          CURRENT_DATE=$(date +"%Y-%m-%d %H:%M:%S UTC")
          COMMIT_MESSAGE="به‌روزرسانی گزارش کانفیگ‌های مشکوک - ${CURRENT_DATE} [skip ci]"

          git commit -m "$COMMIT_MESSAGE"
          
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "درحال پوش کردن تغییرات به شاخه: $CURRENT_BRANCH"
          git push origin "$CURRENT_BRANCH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
