name: Filter Suspicious Configurations (پالایش کانفیگ‌های مشکوک و کامیت گزارش)

on:
  workflow_dispatch: # اجازه اجرای دستی از تب Actions
    inputs:
      links_file_path:
        description: 'مسیر فایل حاوی لیست URLها (نسبت به ریشه مخزن)'
        required: true
        default: 'links.txt'
      report_output_name:
        description: 'نام فایل گزارش اصلی (خلاصه کانفیگ‌های مشکوک) در ریشه مخزن'
        required: true
        default: 'suspicious_configs_report.txt'
  schedule:
    # اجرا روزی یک بار ساعت 5 بعد از ظهر به وقت تهران (13:30 UTC)
    - cron: '30 13 * * *'

env:
  MIN_PERCENT25_COUNT: 15
  MAX_CONFIG_LENGTH: 1500
  PYTHON_SCRIPT_NAME: 'filter_configs.py'
  DETAILS_OUTPUT_DIR_NAME: 'suspicious_config_details'
  STALENESS_REPORT_FILENAME: 'link_staleness_report.txt'
  STATUS_DB_FILENAME: 'link_update_status.json'

jobs:
  filter_and_report:
    name: Filter and Commit Report (فیلتر و کامیت گزارش)
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner (ایمن‌سازی اجراکننده)
        uses: step-security/harden-runner@v2.9.0
        with:
          egress-policy: audit

      - name: Checkout repository (دریافت کد مخزن)
        uses: actions/checkout@v4.1.6

      - name: Set up Python (راه‌اندازی پایتون)
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies (نصب وابستگی‌های پایتون)
        run: pip install requests

      - name: Determine file paths (تعیین مسیرهای فایل)
        id: set_paths
        run: |
          LINKS_FILE="${{ github.event.inputs.links_file_path || 'links.txt' }}"
          MAIN_SUMMARY_REPORT_FILE="${{ github.event.inputs.report_output_name || 'suspicious_configs_report.txt' }}"
          
          echo "LINKS_FILE_TO_USE=$LINKS_FILE" >> $GITHUB_ENV
          echo "MAIN_SUMMARY_REPORT_FILE_TO_USE=$MAIN_SUMMARY_REPORT_FILE" >> $GITHUB_ENV
          
          echo "استفاده از فایل لینک‌ها: $LINKS_FILE"
          echo "گزارش خلاصه کانفیگ‌های مشکوک در: $MAIN_SUMMARY_REPORT_FILE"
          echo "گزارش قدمت لینک‌ها در: ${{ env.STALENESS_REPORT_FILENAME }}"
          echo "پایگاه داده وضعیت لینک‌ها در: ${{ env.STATUS_DB_FILENAME }}"
          echo "فایل‌های جزئیات در پوشه ${{ env.DETAILS_OUTPUT_DIR_NAME }}/"

      - name: Check if links file exists (بررسی وجود فایل لینک‌ها)
        run: |
          if [ ! -f "${{ env.LINKS_FILE_TO_USE }}" ]; then
            echo "::error file=${{ env.LINKS_FILE_TO_USE }}::فایل لینک‌ها یافت نشد."
            exit 1
          fi

      - name: Run configuration filter script (اجرای اسکریپت فیلتر کانفیگ)
        run: |
          python ${{ env.PYTHON_SCRIPT_NAME }} "${{ env.LINKS_FILE_TO_USE }}" "${{ env.MAIN_SUMMARY_REPORT_FILE_TO_USE }}"
          echo "اسکریپت فیلتر اجرا شد."
        env:
          MIN_PERCENT25_COUNT: ${{ env.MIN_PERCENT25_COUNT }}
          MAX_CONFIG_LENGTH: ${{ env.MAX_CONFIG_LENGTH }}

      - name: Commit and push report files (کامیت و پوش کردن فایل‌های گزارش)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id}}+${{ github.actor }}@users.noreply.github.com"

          MAIN_SUMMARY_REPORT_PATH="${{ env.MAIN_SUMMARY_REPORT_FILE_TO_USE }}"
          DETAILS_DIR_PATH="./${{ env.DETAILS_OUTPUT_DIR_NAME }}"
          STALENESS_REPORT_PATH="./${{ env.STALENESS_REPORT_FILENAME }}"
          STATUS_DB_PATH="./${{ env.STATUS_DB_FILENAME }}"

          if [ -f "$MAIN_SUMMARY_REPORT_PATH" ]; then git add "$MAIN_SUMMARY_REPORT_PATH"; fi
          if [ -f "$STALENESS_REPORT_PATH" ]; then git add "$STALENESS_REPORT_PATH"; fi
          if [ -f "$STATUS_DB_PATH" ]; then git add "$STATUS_DB_PATH"; fi
          
          if [ -d "$DETAILS_DIR_PATH" ]; then
            if [ -n "$(ls -A $DETAILS_DIR_PATH)" ]; then
              git add "$DETAILS_DIR_PATH"
            fi
          fi
          
          if git diff --staged --quiet; then
            echo "هیچ تغییری در فایل‌های گزارش برای کامیت کردن وجود ندارد."
            exit 0 
          fi
          
          CURRENT_DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC") # تاریخ و زمان به وقت UTC
          COMMIT_MESSAGE="به‌روزرسانی گزارش‌ها (مشکوک، قدمت، وضعیت) - ${CURRENT_DATE} [skip ci]"

          git commit -m "$COMMIT_MESSAGE"
          
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "درحال پوش کردن تغییرات به شاخه: $CURRENT_BRANCH"
          git push origin "$CURRENT_BRANCH"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
